# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Dweet',
        ),
    ]
