# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190128_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweet',
            name='pub_date',
        ),
    ]
