# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_dweet_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(related_name='_user_follower_+', to='accounts.User'),
        ),
    ]
