# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(to='accounts.User'),
        ),
    ]
