# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190128_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(null=True, to='accounts.User'),
        ),
    ]
