# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190128_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120)),
                ('dweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Dweet')),
            ],
        ),
    ]
