# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190129_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dweet',
        ),
        migrations.AddField(
            model_name='dweet',
            name='comments',
            field=models.ManyToManyField(null=True, to='accounts.Comment'),
        ),
    ]
