# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190129_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='comments',
            field=models.ManyToManyField(to='accounts.Comment'),
        ),
    ]
